ci: fail 을 위한 exit code 추가

diff --git a/.github/workflows/check-pull-request-branch.yml b/.github/workflows/check-pull-request-branch.yml
--- a/.github/workflows/check-pull-request-branch.yml
+++ b/.github/workflows/check-pull-request-branch.yml
@@ -12,4 +12,6 @@ jobs:
     steps:
       - name: check release branch
         if: ${{ github.event.pull_request.head.ref != 'release' }}
-        run: echo "::error ::Not a release branch"
+        run: |
+          echo "::error ::Not a release branch"
+          exit 1;
